# fly.toml
app = "whatsapp-bot-naze"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "3000"
  NODE_ENV = "production"
  TZ = "Asia/Jakarta"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  
  [[http_service.checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = 2000

[processes]
  app = "npm start"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# Volume untuk session persistence
# [[mounts]]
#   source = "whatsapp_sessions"
#   destination = "/app/nazedev"
